services:
  - type: web
    name: kabiero
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
