# Generated by Django 4.2.7 on 2026-03-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='total_amount',
            new_name='tuition_fee',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='lunch_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
    ]
