# Generated by Django 4.2.7 on 2026-03-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
